#SCCatalog.Domain.Entities.Address.dcm.yml
SCCatalog\Domain\Entities\Address:
    type: entity
    table: addresses
    repositoryClass: SCCatalog\Repositories\AddressRepository

    options:
        collate: utf8mb4_unicode_ci
        charset: utf8mb4

    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false

    uniqueConstraints:
        uniq_addresses_uuid:
            columns: [ uuid ]

    indexes:
        idx_street1:
            columns: [ street1 ]
        idx_street2:
            columns: [ street2 ]
        idx_city:
            columns: [ city ]
        idx_state:
            columns: [ state ]
        idx_postal_code:
            columns: [ postal_code ]
        idx_country:
            columns: [ country ]

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
            options:
                unsigned: true

    fields:
        uuid:
            type: guid
        street1:
            type: string
            length: 255
            nullable: true
        street2:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        state:
            type: string
            length: 255
            nullable: true
        postalCode:
            type: string
            column: postal_code
            length: 50
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
        note:
            type: text
            nullable: true
        createdBy:
            type: string
            gedmo:
                blameable:
                    on: create
        updatedBy:
          type: string
          gedmo:
              blameable:
                  on: update
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
